### ISSUE TITLE
750ms delay regardless of resolution

### ISSUE THREAD

**Issue by GregSawin** [eliteio/DS18B20#2]
Looks like the code is waiting 750ms regardless of resolution:
`  delay(750);     // maybe 750ms is enough, maybe not
`
The datasheet as well as other code in the library notes the proper delay per resolution:

      { // lower resolution means shorter conversion time, low bits need masking
        case 0x00: _data[0] &= ~0b111; break;           //  9 bit  93.75 ms
        case 0x20: _data[0] &= ~0b011; break;           // 10 bit 187.50 ms
        case 0x40: _data[0] &= ~0b001; break;           // 11 bit 375.00 ms
        default: break;                                 // 12 bit 750.00 ms

**Comment by ScruffR** [comment]
Finally I came round (was reminded of :blush:) doing this.
0.1.14 should have a dynamic delay. 
But I have not done any extensive testing.
