### ISSUE TITLE
singleDrop example & CRC check can't tell if no sensor

### ISSUE THREAD

**Issue by GregSawin** [eliteio/DS18B20#3]
I was trying the single drop example and noticed if I removed the DS18B20 sensor or had the wrong pin assigned there's no error, just a bunch of nan reporting.   I'm a bit surprised that the CRC check doesn't fail, how could there even be a CRC check if the chip doesn't exist or isn't powered.

I've also seen other cases where an obviously bad value slips through the CRC check, for example -1518C.

**Comment by ScruffR** [comment]
I haven't payed too much attention on how the original library (which I took over from someone else) does the CRC calculation, but if it only adds up the bytes (or some similar scheme) without any non-zero part (e.g. a magic number) `0 == 0` would render a "valid" checksum.
Also other combinations of bytes can provide a false positive.
But if that's how the sensor internally calculates the CRC then there is little that can be done.

Nevertheless, I'll have a look what's actually going on.
