### ISSUE TITLE
Upgrade OneWire dependency to support gen 3 devices

### ISSUE THREAD

**Issue by lucamora** [eliteio/DS18B20#4]
With the current dependency OneWire@2.0.3 I've encountered more or less 10% of failed CRC checks on Boron/Xenon

In OneWire@2.0.4 Particle added support to gen 3 devices and with that version I experienced no issues and all measurements seem to be successful

**Comment by ScruffR** [comment]
Done - can you test and report back please?

**Comment by lucamora** [comment]
Tested on Xenon and Boron with 500 measures and never failed!
Thank you very much for the fix
